global:
  labels:
    training: block5
  ports:
    name: http
    protocol: TCP
    port: 8080

frontapp:
  replicaCount: 1
  labels:
    homework: frontapp
  image:
    repository: quay.io/drsylent/cubix/block3/homework-frontapp
    tag: springboot3
  host:
    test: other.cubix.localhost
    prod: application.cubix.localhost
  pathPrefix: /
  env:
    - name: APP_DEFAULT_MESSAGE
      value: "frontapp"
    - name: JAVA_OPTS
      value: ""
  backUrl: http://backapp:8080
  containerPort: 8080

backapp:
  replicaCount: 1
  labels:
    homework: backapp
  image:
    repository: quay.io/drsylent/cubix/block3/homework-backapp
    tag: springboot3
  env:
    - name: APP_DEFAULT_MESSAGE
      value: "backapp"
    - name: JAVA_OPTS
      value: ""
  containerPort: 8080
