global:
  labels:
    training: block5

frontapp:
  replicaCount: 1
  labels:
    homework: frontapp
  image:
    repository: quay.io/drsylent/cubix/block3/homework-frontapp
    tag: springboot3
  host:
    test: other.cubix.localhost
    prod: application.cubix.localhost
  pathPrefix: /
  ports:
    name: http
    protocol: TCP
    port: 8080
  appDefaultMessage: "frontapp"
  javaOpts: ""
  env: []

backapp:
  replicaCount: 1
  labels:
    homework: backapp
  image:
    repository: quay.io/drsylent/cubix/block3/homework-backapp
    tag: springboot3
  ports:
    name: http
    protocol: TCP
    port: 8080
  appDefaultMessage: "backapp"
  javaOpts: ""
  env: []
