apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw5-chart.fullname" . }}-{{ .Values.backapp.labels.homework }}
  labels:
    homework: {{ .Values.backapp.labels.homework }}
    training: {{ .Values.global.labels.training }}
spec:
  selector:
    homework: {{ .Values.backapp.labels.homework }}
    training: {{ .Values.global.labels.training }}
  ports:
    - name: {{ .Values.backapp.ports.name }}
      protocol: {{ .Values.backapp.ports.protocol }}
      port: {{ .Values.backapp.ports.port }}
      targetPort: {{ .Values.backapp.ports.port }}
  type: ClusterIP
